name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '20'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.13.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: bump_version
    - name: Build and publish Docker Image
      run: |
        echo "@fortawesome:registry=https://npm.fontawesome.com/
        //npm.fontawesome.com/:_authToken=$FA_TOKEN" > .npmrc
        make build
        docker login docker.pkg.github.com -u anothrNick -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
        docker tag machinable-ui_ui:latest docker.pkg.github.com/machinable/machinable-ui/ui:$REACT_APP_VERSION
        docker push docker.pkg.github.com/machinable/machinable-ui/ui:$REACT_APP_VERSION
      env:
        REACT_APP_VERSION: ${{ steps.bump_version.outputs.new_tag }}
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FA_TOKEN: ${{ secrets.FA_TOKEN }}
